options:
  vsm_ip:
    type: string
    default: "172.23.181.82"
    description: "Management ip of VSM"
  vsm_domain_id:
    type: int
    default: 101
    description: "Domain id this vsm will be controlling"
  host_mgmt_intf:
    type: string
    default: "eth1"
    description: "Management interface of the Host"
  uplink_profile:
    type: string
    default: "phys eth1 profile sys-uplink"
    description: "Port-Profile mapping for all UVEM managed Interfaces"
  vtep_config:
    type: string
    default: ""
    description: "VTEP config. Syntax: virt <port-name> profile <profile-name> [mode static|dhcp] [address <ipaddr>]"
  node_type:
    type: string
    default: "compute"
    description: "Function of this node in Cisco Openstack network"
  mapping:
    type: string
    default: ""
    description: "Host Specific configuration mapping"
