#!/bin/sh
#This is an example of openrc
# READ:http://docs.openstack.org/user-guide/content/cli_openrc.html
export OS_NO_CACHE=true
export OS_TENANT_NAME=admin
export OS_USERNAME={{ os_username }}
export OS_PASSWORD={{ os_password }}
export OS_AUTH_URL=http://{{ service_host }}:{{ service_port }}/v2.0/  
export OS_AUTH_STRATEGY=keystone
export OS_REGION_NAME=RegionOne
export CINDER_ENDPOINT_TYPE=publicURL
export GLANCE_ENDPOINT_TYPE=publicURL
export KEYSTONE_ENDPOINT_TYPE=publicURL
export NOVA_ENDPOINT_TYPE=publicURL
export QUANTUM_ENDPOINT_TYPE=publicURL
