options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  rabbit-user:
    default: nova
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    decsription: Rabbitmq vhost
  database-user:
    default: nova
    type: string
    description: Username for database access
  database:
    default: nova
    type: string
    description: Database name
  neutron-database-user:
    default: neutron
    type: string
    description: Username for Neutron database access (if enabled)
  neutron-database:
    default: neutron
    type: string
    description: Database name for Neutron (if enabled)
  network-manager:
    default: FlatDHCPManager
    type: string
    description: |
      Network manager for the cloud; supports the following options
      .
        FlatDHCPManager (nova-network) (default)
        FlatManager (nova-network)
        Neutron|Quantum (Full SDN solution)
      .
      When using the Neutron option you will most likely want to use
      the neutron-gateway charm to provide L3 routing and DHCP Services.
  bridge-interface:
    default: br100
    type: string
    description: Bridge interface to be configured
  bridge-ip:
    default: 11.0.0.1
    type: string
    description: IP to be assigned to bridge interface
  bridge-netmask:
    default: 255.255.255.0
    type: string
    description: Netmask to be assigned to bridge interface
  quantum-plugin:
    default: ovs
    type: string
    description: |
      Quantum plugin to use for network management; supports
      .
        ovs - OpenvSwitch Plugin
        nvp - Nicira Network Virtualization Platform
        n1kv - Cisco Network Virtualization Platform
      .
      This configuration only has context when used with
      network-manager Quantum.
  quantum-security-groups:
    type: string
    default: "no"
    description: |
      Use quantum for security group management.
      .
      Only supported for >= grizzly.
  neutron-external-network:
    type: string
    default: ext_net
    description: Name of the external network for floating IP addresses provided by Neutron.
  config-flags:
    default: None
    type: string
    description: Comma separated list of key=value config flags to be set in nova.conf.
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  # HA configuration settings
  vip:
    type: string
    description: "Virtual IP to use to front API services in ha configuration"
  vip_iface:
    type: string
    default: eth0
    description: "Network Interface where to place the Virtual IP"
  vip_cidr:
    type: int
    default: 24
    description: "Netmask that will be used for the Virtual IP"
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5404
    description: |
       Default multicast port number that will be used to communicate between
       HA Cluster nodes.
  ssl_cert:
    type: string
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Glance's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    description: SSL key to use with certificate specified as ssl_cert.
  # Neutron NVP Plugin configuration
  nvp-controllers:
    type: string
    description: Space delimited addresses of NVP controllers
  nvp-username:
    type: string
    default: admin
    description: Username to connect to NVP controllers with
  nvp-password:
    type: string
    default: admin
    description: Password to connect to NVP controllers with
  nvp-cluster-name:
    type: string
    default: example
    description: Name of the NVP cluster configuration to create (grizzly only)
  nvp-tz-uuid:
    type: string
    description: |
      This is uuid of the default NVP Transport zone that will be used for
      creating tunneled isolated Quantum networks.  It needs to be created
      in NVP before starting Quantum with the nvp plugin.
  nvp-l3-uuid:
    type: string
    description: |
      This is uuid of the default NVP L3 Gateway Service.
  # end of NVP configuration
  n1kv-vsm-username:
    type: string
    default: admin
    description: Username to connect to cisco n1kv VSM
  n1kv-vsm-password:
    type: string
    default: Sfish123 
    description: Password to connect to cisco n1kv VSM 
  n1kv-vsm-ip:
    type: string
    default: 10.10.10.10
    description: IP to connect to cisco n1kv VSM 
  n1kv-source:
    type: string
    default: distro
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - deb http://my.archive.com/ubuntu main|KEYID
      .
      Note that this is used only for Cisco n1kv plugin.
  keystone-usrname:
    type: string
    default: admin
    description: Username to connect to keystone
  keystone-password:
    type: string
    default: openstack
    description: Password to connect to keystone
