#!/usr/bin/env python2
# -*- python -*-

# This file is part of the Juju GUI, which lets users view and manage Juju
# environments within a graphical interface (https://launchpad.net/juju-gui).
# Copyright (C) 2012-2013 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License version 3, as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranties of MERCHANTABILITY,
# SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

from charmhelpers import (
    get_config,
    log,
)
from shelltoolbox import DictDiffer

from backend import Backend
from utils import (
    config_json,
    log_hook,
)


def main():
    config = get_config()
    prev_config = config_json.get()
    diff = DictDiffer(config, prev_config)
    if not diff.modified:
        log("No configuration changes, exiting.")
        sys.exit(0)

    log('Updating configuration.')
    backend = Backend(config, prev_config)
    if prev_config:
        # Stop whatever the old config was.
        prev_backend = Backend(prev_config)
        prev_backend.stop()
    backend.install()
    backend.start()

    # Record new configuration
    config_json.set(config)


if __name__ == '__main__':
    with log_hook():
        main()
