#!/usr/bin/env python2
# -*- python -*-

# Copyright 2013 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from charmhelpers import (
    get_config,
    log,
)

from backend import Backend
from utils import (
    config_json,
    log_hook,
)


# Charm dependency changes that are found in the install hook are not handled.
def main():
    config = get_config()
    prev_config = config_json.get()
    log('Upgrading charm.')
    backend = Backend(config, prev_config)
    backend.install()
    if prev_config:
        # Stop whatever the old config was.
        prev_backend = Backend(prev_config)
        prev_backend.stop()
    backend.start()
    # Record new configuration
    config_json.set(config)


if __name__ == '__main__':
    with log_hook():
        main()
