#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

apt-get update
#Instaling dependencies
apt-get install -y libnl1
apt-get install -y build-essential
apt-get install -y linux-headers-`uname -r` linux-headers-generic
#apt-get install -y openvswitch-switch qemu-kvm libvirt-bin virtinst dkms 
apt-get install -f -y openvswitch-common=1.4.0-1ubuntu1.5 openvswitch-switch=1.4.0-1ubuntu1.5  
apt-mark hold openvswitch-common openvswitch-switch

#creating n1kv.conf
mkdir /etc/n1kv
echo "uvem-ovs-brname br-int" > /etc/n1kv/n1kv.conf

tee /etc/apt/sources.list.d/springfield-ppa.list <<EOF
deb https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main #Personal access of Shiv Prasad Rao (shivrao) to Cisco Nexus 1000v Staging PPA
deb-src https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main #Personal access of Shiv Prasad Rao (shivrao) to Cisco Nexus 1000v Staging PPA
EOF
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F5DB2BA06DB3EEB4 
apt-get update
ovs-vsctl -- --may-exist add-br br-int -- set-fail-mode br-int secure
apt-get install --force-yes -y nexus-1000v-vem-dkms
apt-get install --force-yes -y nexus-1000v-vem


