#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

apt-get update
apt-get install -y libnl1
apt-get install -y build-essential
apt-get install -y linux-headers-`uname -r` linux-headers-generic
apt-get install -y openvswitch-switch qemu-kvm libvirt-bin virtinst dkms 
#apt-get install -y  qemu-kvm libvirt-bin virtinst dkms

mkdir /etc/n1kv
touch /etc/n1kv/n1kv.conf

#mv /etc/apt/apt.conf /etc/apt/apt.conf.tmp
tee /etc/apt/sources.list.d/springfield-ppa.list <<EOF
deb https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main #Personal access of Shiv Prasad Rao (shivrao) to Cisco Nexus 1000v Staging PPA
deb-src https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main #Personal access of Shiv Prasad Rao (shivrao) to Cisco Nexus 1000v Staging PPA
EOF
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F5DB2BA06DB3EEB4 
apt-get update
apt-get install -y nexus-1000v-vem-dkms
apt-get install -y nexus-1000v-vem
#mv /etc/apt/apt.conf.tmp /etc/apt/apt.conf


