#!/bin/bash

for rid in $( relation-ids dvs ); do
    juju-log "Relation-set for $rid"
    xvsm_domain_id=$(config-get domainid)
    xvsm_ip=$(config-get mgmtip)
    #rid=$(relation-ids dvs)
    relation-set -r $rid vsm_domain_id=$xvsm_domain_id
    relation-set -r $rid vsm_ip=$xvsm_ip
done
