#!/bin/bash

function add_havana_apt_repo {
     juju-log "Install python-software-properties"
     sudo sudo apt-get install -y python-software-properties
     juju-log "Installing python-software-properties done"

     juju-log "Install add-apt-repo cloud-archive:havana"
     sudo add-apt-repository -y cloud-archive:havana
     juju-log "Installing add-apt-repo cloud-archive:havana done"

     juju-log "Install add-apt-repo cloud-archive:havana"
     sudo apt-get update
     juju-log "apt-get update done"

     juju-log "Install add-apt-repo cloud-archive:havana"
     sudo apt-cache policy openvswitch-switch
     juju-log "installing openvswitch-switch done"
}

#Install the dependency packages
function install_vsm_dependency_pacakges {
    juju-log "Starting with installation of vsm dependency packages"

    #Install the kernel_hdr_pkg based on the kernel version
    kernel_release=`uname -r`
    juju-log "kernel_release is $kernel_release"
    kernel_hdr_pkg="linux-headers-$kernel_release"
    juju-log "kernel_hdr_okg is $kernel_hdr_pkg"

    sudo apt-get install -y $kernel_hdr_pkg

    #Install the kvm package
    juju-log "Install the kvm package"
    sudo apt-get install -y kvm

    #Install the libvirt-bin package
    juju-log "Install the libvirt-bin package"
    sudo apt-get install -y libvirt-bin

    #Install the virtinst package
    juju-log "Install the virtinst package"
    sudo apt-get install -y virtinst

    #Install the genisoimage package
    juju-log "Install the kvm package"
    sudo apt-get install -y genisoimage

    #Install the python-cheetah package
    juju-log "Install the python-cheetah package"
    sudo apt-get install -y python-cheetah
}

#Remove and disable auto start for virsh network
function vish_remove_network {
    #Remove virsh network
    if test -e /usr/bin/virsh; then

      juju-log "remove the virsh network"
      virsh_net=`/usr/bin/virsh net-info default | grep -c 'Active: .* no'`
      juju-log "virsh_net is $virsh_net"
      if [ $virsh_net -eq 0 ]; then
        /usr/bin/virsh net-destroy default
      fi

      #Disable the virsh autostart
      juju-log "disable the virsh net-autostart"
      virsh_auto=`/usr/bin/virsh net-info default | grep -c 'Autostart: .* no'`
      juju-log "virsh_auto is $virsh_auto"
      if [ $virsh_auto -eq 0 ]; then
        /usr/bin/virsh net-autostart --disable default
      fi

    fi

    juju-log "purge the ebtables"
    aptitude -y purge ebtables
}

#Install the OVS components
function install_ovs_components {

    #Install the ovs components and all dependency packages
    juju-log "Install the OVS components [openvswitch switch & datapath source & dkms]"
    sudo apt-get install -y openvswitch-switch openvswitch-datapath-source openvswitch-datapath-dkms

    #check and install the openvswitch-data for the kernel version
    juju-log "Install openvswitch-data based on kernel version"
    kernel_release=`uname -r`
    datapath=`/usr/bin/dpkg -s openvswitch-datapath-module-${kernel_release} | grep -c '^Status: install ok installed'`
    if [ $datapath -eq 0 ]; then
      module-assistant prepare
      /usr/bin/module-assistant --text-mode auto-install openvswitch-datapath
    fi

    #This step is not required with 1.10.2 openvswitch-switch
    #juju-log "Update BRCOMPAT to yes in /etc/default/openvswitch-switch"
    #cheetah fill --env --oext compiled templates/openvswitch-switch.tmpl
    #cp templates/openvswitch-switch.compiled /etc/default/openvswitch-switch

    juju-log "Done with installation of ovs components"
}

#Start the install hook
add_havana_apt_repo
install_vsm_dependency_pacakges
vish_remove_network
install_ovs_components

#Create the vsm directory in /var/spool
if [ ! -d /var/spool/vsm ]; then
    juju-log "Create the /var/spool/vsm directory"
    mkdir /var/spool/vsm
fi
