#!/bin/bash
# This hook is run directly after install
# i.e. 'service apache2 start'

function create_vsm_vm {
    logger "Check and virsh create the vsm vm"
    vsm_running=`/usr/bin/virsh list | grep -c ' $vsmname .* running'`

    if [ $vsm_running -eq 0 ]; then
      /usr/bin/virsh create /var/spool/vsm/vsm_vm.xml
      logger "virsh create of vsm vm done"
    fi

}

create_vsm_vm
