options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  database-user:
    default: glance
    type: string
    description: Database username
  database:
    default: glance
    type: string
    description: Glance database name.
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  ceph-osd-replication-count:
    default: 2
    type: int
    description: |
      This value dictates the number of replicas ceph must make of any
      object it stores within the images rbd pool. Of course, this only
      applies if using Ceph as a backend store. Note that once the images
      rbd pool has been created, changing this value will not have any
      effect (although it can be changed in ceph by manually configuring
      your ceph cluster).
  # HA configuration settings
  vip:
    type: string
    description: "Virtual IP to use to front Glance API in ha configuration"
  vip_iface:
    type: string
    default: eth0
    description: "Network Interface where to place the Virtual IP"
  vip_cidr:
    type: int
    default: 24
    description: "Netmask that will be used for the Virtual IP"
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5402
    description: |
      Default multicast port number that will be used to communicate between
      HA Cluster nodes.
  ssl_cert:
    type: string
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Glance's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    description: SSL key to use with certificate specified as ssl_cert.
  rabbit-user:
    default: glance
    type: string
    description: Username to request access on rabbitmq-server.
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ virtual host to request access on rabbitmq-server.

