{!!python/unicode 'cisco_plugins.ini': {!!python/unicode 'vswitch_plugin': !!python/unicode 'quantum.plugins.cisco.n1kv.n1kv_quantum_plugin.N1kvQuantumPluginV2',
    !!python/unicode '': !!python/unicode 'phys eth1 profile sys-uplink',
    !!python/unicode 'vsm_domain_id': !!python/unicode '1', !!python/unicode 'vsm_ip': !!python/unicode '0.0.0.0'}}
