#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

function load_vxgw_to_glance {
source /root/openrc
FILENAME=/opt/cisco/n1kv/vxgw/vxgw.5.2.1.SK1.2.1.disk1.qcow2
    if [ -f $FILENAME ]; then
        glance image-create --name=vx-gw --is-public=true --property hw_vif_model=virtio --property hw_disk_bus=ide --property hw_cdrom_bus=ide --container-format=ovf --disk-format=qcow2 < $FILENAME
    fi
#glance image-create --name vx-gw --disk-format qcow2 --container-format bare --is-public True < /tmp/$(config-get vxgw-img-name)
}

load_vxgw_to_glance
