#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

function load_vxgw_to_glance {
  FILENAME=`ls /opt/cisco/n1kv/vxgw/*`

  if [ -f $FILENAME ]; then
    FILESIZE=$(stat -c%s "$FILENAME")
    FILESIZE_LIMIT=118000000
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
      sleep 5
    fi
   
    openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'`
    TIMEOUT=30
    while [ "$openrc_ready" = ":" ]; do
      sleep 60
      TIMEOUT=$((TIMEOUT - 1))
      openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'`
      if [ "$TIMEOUT" -eq "0" ]; then
        exit 1
      fi
    done

    source /root/openrc
    glance image-create --name=vx-gw --is-public=true --property hw_vif_model=virtio --property hw_disk_bus=ide --property hw_cdrom_bus=ide --container-format=ovf --disk-format=qcow2 < $FILENAME
  else
    exit 1
  fi
#glance image-create --name vx-gw --disk-format qcow2 --container-format bare --is-public True < /tmp/$(config-get vxgw-img-name)
}

load_vxgw_to_glance
