#!/bin/bash
# Here do anything needed to install the service
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.


function add_repo {
  # get the source from input config.
  source=$(config-get n1kv-source)
  if [ "$source" == "distro" ]; then
    exit 1
  fi

  arr_source=($source)  
  if [ ${arr_source[0]} == 'deb' ];then
    key=`cut -d "|" -f 2 <<< "$source"`
    deb_source=`cut -d "|" -f 1 <<< "$source"`
    echo $deb_source >> /etc/apt/sources.list.d/springfield-ppa.list
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $key
  fi
}

function download_vxgw {
  apt-get update
  version=$(config-get vxgw-img-version)
  apt-get install -y vxgw

  if [ "$version" != "latest" ];then
    FILENAME=/opt/cisco/n1kv/vxgw/"vxgw.5.2.1.SK1."$version".disk1.qcow2"
  else
    PKG_NAME=`ls -t vxgw.5.2.1.SK1.* | head -1`
    FILENAME=/opt/cisco/n1kv/vxgw/$PKG_NAME
  fi

  while [ ! -f $FILENAME ]; do
    sleep 1
  done

  FILESIZE=$(stat -c%s "$FILENAME")
  FILESIZE_LIMIT=118000000
  if [ -f $FILENAME ]; then
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
        sleep 5    
    fi
  fi
}

download_vxgw
