#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

function download_vxgw {
  apt-get update
  version=$(config-get vxgw-img-version)
  juju-log "Installing vxgw"
  apt-get install -y vxgw
  if [ "$version" != "latest" ];then
    FILENAME=/opt/cisco/n1kv/vxgw/"vxgw.5.2.1.SK1."$version".disk1.qcow2"
  else
    PKG_NAME=`ls -t vxgw.5.2.1.SK1.* | head -1`
    FILENAME=/opt/cisco/n1kv/vxgw/$PKG_NAME
  fi
  while [ ! -f $FILENAME ]; do
    sleep 2
  done

  FILESIZE=$(stat -c%s "$FILENAME")
  FILESIZE_LIMIT=118000000
  if [ -f $FILENAME ]; then
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
        sleep 5
    fi
  fi
}

function load_vxgw_to_glance {

  source /root/openrc

  version=$(config-get vxgw-img-version)
  if [ "$version" != "latest" ];then
    FILENAME=/opt/cisco/n1kv/vxgw/"vxgw.5.2.1.SK1."$version".disk1.qcow2"
  else
    PKG_NAME=`ls -t vxgw.5.2.1.SK1.* | head -1`
    FILENAME=/opt/cisco/n1kv/vxgw/$PKG_NAME
  fi
  if [ -f $FILENAME ]; then
    FILESIZE=$(stat -c%s "$FILENAME")
    FILESIZE_LIMIT=118000000
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
        sleep 5
    fi

    openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'`
    TIMEOUT=10
    while [ "$openrc_ready" = ":" ]; do
      sleep 5
      TIMEOUT=$((TIMEOUT - 1))
      echo $TIMEOUT
      openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'`
      if [ "$TIMEOUT" = "0" ]; then
        juju-log "Incomplete openrc.please upload manually"
        exit 1
      fi
    done
    juju-log "source openrc"
    source /root/openrc
    juju-log "upload vxgw image"

    glance image-create --name=vx-gw --is-public=true --property hw_vif_model=virtio --property hw_disk_bus=ide --property hw_cdrom_bus=ide --container-format=ovf --disk-format=qcow2 < $FILENAME
  fi
#glance image-create --name vx-gw --disk-format qcow2 --container-format bare --is-public True < /tmp/$(config-get vxgw-img-name)
}

download_vxgw
load_vxgw_to_glance

